# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 02:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField(verbose_name='Graduation year')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Organization name')),
                ('region', models.CharField(blank=True, max_length=32, verbose_name='Organization location')),
                ('type', models.CharField(choices=[('ED', 'Education'), ('BS', 'Business')], default='BS', max_length=2, verbose_name='Organization type')),
                ('site', models.CharField(blank=True, max_length=32, verbose_name='Organization website')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=16, verbose_name='Fist name')),
                ('lastname', models.CharField(max_length=16, verbose_name='Last name')),
                ('born', models.DateField(blank=True, verbose_name='Date of birth')),
                ('place', models.CharField(max_length=32, verbose_name='Place of birth')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.PositiveIntegerField(default=1, verbose_name='Work length, months')),
                ('position', models.CharField(max_length=16, verbose_name='Position')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Organization', verbose_name='Organization name')),
            ],
        ),
        migrations.AddField(
            model_name='education',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.Organization', verbose_name='Organization name'),
        ),
    ]
